apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: identity
  namespace: deckhub
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: identity
    spec:
      containers:
      - image: deckhub/id:1.0.0-alpha7
        imagePullPolicy: Always
        name: identity
        env:
          - name: Redis__Host
            value: 'redis'
          - name: Runtime__PathBase
            value: '/identity'
          - name: AppMetrics__InfluxDbServer
            value: 'http://rlmetrics.eastus.cloudapp.azure.com:8086'
          - name: AppMetrics__InfluxDbDatabase
            value: 'deckhub'
          - name: ConnectionStrings__Identity
            valueFrom:
              secretKeyRef:
                name: identity-db
                key: connstr
          - name: Authentication__Twitter__ConsumerKey
            valueFrom:
              secretKeyRef:
                name: twitter
                key: consumerKey
          - name: Authentication__Twitter__ConsumerSecret
            valueFrom:
              secretKeyRef:
                name: microsoft
                key: applicationId
          - name: Authentication__Microsoft__ApplicationId
            valueFrom:
              secretKeyRef:
                name: microsoft
                key: password
          - name: Authentication__Microsoft__Password
            valueFrom:
              secretKeyRef:
                name: twitter
                key: consumerSecret
          - name: Security__ApiKeyHashPhrase
            valueFrom:
              secretKeyRef:
                name: api-key
                key: hashPhrase
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: identity
  namespace: deckhub
spec:
  ports:
  - port: 80
    protocol: TCP
    name: http
  selector:
    app: identity
  sessionAffinity: ClientIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: identity
  namespace: deckhub
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: deckhub.app
    http:
      paths:
      - path: /Identity
        backend:
          serviceName: identity
          servicePort: 80
      - path: /identity
        backend:
          serviceName: identity
          servicePort: 80