apiVersion: batch/v1
kind: Job
metadata:
  name: identity-migrate
  namespace: deckhub
spec:
  template:
    metadata:
      name: identity-migrate
    spec:
      containers:
      - name: identity-migrate
        image: deckhub/identity-migrate:1.0.0-alpha2
        args: ["$(SECRET_CONNSTR)"]
        env:
          - name: SECRET_CONNSTR
            valueFrom:
              secretKeyRef:
                name: identity-db
                key: connstr
      restartPolicy: OnFailure